name: Update Data Text File

on:
  schedule:
    - cron: '0 6 * * *'  # Run daily at 6:00 AM UTC
  workflow_dispatch:  # Manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client

    - name: Run Python script to update data.txt
      env:
        SHEET_URL: ${{ secrets.SHEET_URL }}
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      run: |
        python update_data_txt.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add data.txt
        git commit -m "Update data.txt"
        git push
