name: Update Data Text File

on:
  schedule:
    - cron: '0 6 * * *'  # Run daily at 6:00 AM UTC
  workflow_dispatch:  # Manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Prepare credentials file
      env:
        CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
      run: |
        echo "$CREDENTIALS_JSON" > credentials.json

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client

    - name: Run Python script to update data.txt
      run: |
        python update_data_txt.py

    - name: Push changes to GitHub Pages
      run: |
        git fetch origin
        git checkout gh-pages || git checkout --orphan gh-pages
        git pull origin gh-pages --rebase || echo "gh-pages branch is new."
        git add data.txt
        git commit -m "Update data.txt for GitHub Pages" || echo "No changes to commit."
        git push origin gh-pages
  
